version: '3.7'

services:
  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16.3
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - app_cache_data:/data

volumes:
  app_db_data:
    driver: "local"
  app_cache_data:
    driver: "local"
